kind: pipeline
type: docker
name: docker

clone:
  disable: true

steps:
  - name: clone
    image: drone/git
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
      DRONE_REMOTE_URL: ${DOWNSTREAM_DRONE_REMOTE_URL}
      DRONE_BUILD_EVENT: ${DOWNSTREAM_BUILD_EVENT}
      DRONE_COMMIT_SHA: ${DOWNSTREAM_DRONE_COMMIT_SHA}
      DRONE_COMMIT_BRANCH: ${DOWNSTREAM_DRONE_COMMIT_BRANCH}
      DRONE_COMMIT_REF: ${DOWNSTREAM_DRONE_COMMIT_REF}
    commands:
      - mkdir -p $HOME/.ssh && echo "$SSH_KEY" > $HOME/.ssh/id_rsa && chmod 0600 $HOME/.ssh/id_rsa
      - ssh-keyscan github.com > ~/.ssh/known_hosts
      - /usr/local/bin/clone
      - git pull
      
  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - cd $DRONE_WORKSPACE/mtb-dirt/Assets
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.9.2/ls-lint-linux && chmod +x ls-lint && ./ls-lint

  - name: sln
    image: unityci/editor:ubuntu-2020.3.2f1-linux-il2cpp-0.11.0
    environment:
      UNITY_USERNAME:
        from_secret: UNITY_USERNAME
      UNITY_PASSWORD:
        from_secret: UNITY_PASSWORD
      UNITY_LICENSE:
        from_secret: UNITY_LICENSE
    commands:
      - mkdir -p $HOME/.cache/unity3d
      - mkdir -p $HOME/.local/share/unity3d/Unity/
      - echo 'Writing $UNITY_LICENSE to license file $HOME/.local/share/unity3d/Unity/Unity_lic.ulf'
      - echo "$UNITY_LICENSE" | tr -d '\r' > $HOME/.local/share/unity3d/Unity/Unity_lic.ulf
      - (cd $DRONE_WORKSPACE/mtb-dirt/Assets && WORKSPACE=$DRONE_WORKSPACE make sync)
      
  - name: resharper
    image: unityci/editor:ubuntu-2020.3.2f1-linux-il2cpp-0.11.0
    commands:
      - export PATH=/usr/local/share/dotnet:$PATH
      - (cd $DRONE_WORKSPACE/mtb-dirt/Assets && WORKSPACE=$DRONE_WORKSPACE make resharper-install)
      - (cd $DRONE_WORKSPACE/mtb-dirt/Assets && WORKSPACE=$DRONE_WORKSPACE make resharper-inspectcode)

