kind: pipeline
type: docker
name: docker

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
      SOURCE_HASH:
    commands:
      - mkdir -p $HOME/.ssh && echo "$SSH_KEY" > $HOME/.ssh/id_rsa && chmod 0600 $HOME/.ssh/id_rsa
      - ssh-keyscan github.com > ~/.ssh/known_hosts
      - git config --global init.defaultBranch main
      - cd $DRONE_WORKSPACE && git init mtb-dirt
      - cd $DRONE_WORKSPACE/mtb-dirt
      - git config pull.rebase false
      - git remote add origin git@github.com:loeffel-io/mtb-dirt.git
      #- git config core.sparsecheckout true
      #- echo "Assets/Imports/*" >> .git/info/sparse-checkout
      #- echo "Assets/Src/*" >> .git/info/sparse-checkout
      #- echo "Assets/.ls-lint.yml" >> .git/info/sparse-checkout
      #- echo "Assets/Makefile" >> .git/info/sparse-checkout
      - git pull origin main
      #- git fetch origin $SOURCE_HASH
      #- git checkout -b temp FETCH_HEAD

  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - cd $DRONE_WORKSPACE/mtb-dirt/Assets
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.9.2/ls-lint-linux && chmod +x ls-lint && ./ls-lint

  - name: sln
    image: unityci/editor:ubuntu-2020.3.2f1-linux-il2cpp-0.11.0
    environment:
      UNITY_USERNAME:
        from_secret: UNITY_USERNAME
      UNITY_PASSWORD:
        from_secret: UNITY_PASSWORD
      UNITY_LICENSE:
        from_secret: UNITY_LICENSE
    commands:
      - mkdir -p $HOME/.cache/unity3d
      - mkdir -p $HOME/.local/share/unity3d/Unity/
      - echo 'Writing $UNITY_LICENSE to license file $HOME/.local/share/unity3d/Unity/Unity_lic.ulf'
      - echo "$UNITY_LICENSE" | tr -d '\r' > $HOME/.local/share/unity3d/Unity/Unity_lic.ulf
      - (cd $DRONE_WORKSPACE/mtb-dirt/Assets && WORKSPACE=$DRONE_WORKSPACE make sync)
      # - /opt/unity/Editor/Unity -batchmode -nographics -manualActivation -logFile /dev/stdout -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD".,
      # - /opt/unity/Editor/Unity -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD" -batchmode -nographics -manualLicenseFile $HOME/Unity_v2020.x.ulf -logFile
      
  - name: resharper
    image: unityci/editor:ubuntu-2020.3.2f1-linux-il2cpp-0.11.0
    commands:
      - (cd $DRONE_WORKSPACE/mtb-dirt/Assets && WORKSPACE=$DRONE_WORKSPACE make resharper-install)
      - (cd $DRONE_WORKSPACE/mtb-dirt/Assets && WORKSPACE=$DRONE_WORKSPACE make resharper-inspectcode)

