kind: pipeline
type: docker
name: docker

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
      SOURCE_HASH:
    commands:
      - env
      - apk add openssh
      - mkdir -p $HOME/.ssh && echo "$SSH_KEY" > $HOME/.ssh/id_rsa && chmod 0600 $HOME/.ssh/id_rsa
      - ssh-keyscan github.com > $HOME/.ssh/known_hosts
      - git config --global init.defaultBranch main
      - git init mtb-dirt
      - cd mtb-dirt
      - git config pull.rebase false
      - git remote add origin git@github.com:loeffel-io/mtb-dirt.git
      - git config core.sparsecheckout true
      - echo "Assets/Src/*" >> .git/info/sparse-checkout
      - echo "Assets/.ls-lint.yml" >> .git/info/sparse-checkout
      - echo "Assets/Makefile" >> .git/info/sparse-checkout
      - git pull origin main
      #- git fetch origin $SOURCE_HASH
      #- git checkout -b temp FETCH_HEAD

  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - cd mtb-dirt/Assets
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.9.2/ls-lint-linux && chmod +x ls-lint && ./ls-lint